name: .NET CI/CD

on:
  push:
    branches: [ "main", "develop" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main", "develop" ]
  release:
    types: [published]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Normalize Line Endings
        run: |
          git config --global core.autocrlf false
          git config --global core.eol crlf
          git add --renormalize .
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Run linter
        run: dotnet format --verify-no-changes --verbosity diagnostic
        
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.11
      with:
        versionSpec: '6.0.x'
        preferLatestVersion: true

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@v3.1.11
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: |
        dotnet build --configuration Release --no-restore \
        /p:Version=${{ steps.gitversion.outputs.fullSemVer }} \
        /p:AssemblyVersion=${{ steps.gitversion.outputs.assemblySemVer }} \
        /p:FileVersion=${{ steps.gitversion.outputs.assemblySemFileVer }} \
        /p:InformationalVersion=${{ steps.gitversion.outputs.informationalVersion }}
